<?php

return [
    [
        'title' => 'Список пользователей',
        'url' => 'users.php',
        'category' => 'Пользователи',
        'desc' => 'Общий реестр аккаунтов, статусы, поиск и быстрый переход к профилям.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Глубокий поиск пользователей',
        'url' => 'usersearch.php',
        'category' => 'Пользователи',
        'desc' => 'Расширенные фильтры по профилям, активности и служебным данным.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Пароли и почта',
        'url' => 'admincp.php?op=iusers',
        'category' => 'Пользователи',
        'desc' => 'Смена пароля и e-mail для выбранного пользователя из админки.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Добавить пользователя',
        'url' => 'adduser.php',
        'category' => 'Пользователи',
        'desc' => 'Создание аккаунта вручную с выдачей нужного класса и данных.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Смена класса',
        'url' => 'setclass.php',
        'category' => 'Пользователи',
        'desc' => 'Повышение, понижение и раздача системных прав пользователям.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Предупреждённые пользователи',
        'url' => 'warned.php',
        'category' => 'Пользователи',
        'desc' => 'Контроль активных предупреждений и сроков их снятия.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Удаление аккаунтов',
        'url' => 'delacctadmin.php',
        'category' => 'Пользователи',
        'desc' => 'Административное удаление пользователей с проверкой причины.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Аплоадеры',
        'url' => 'uploaders.php',
        'category' => 'Пользователи',
        'desc' => 'Список и сопровождение заливающих пользователей.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Инвайты',
        'url' => 'inviteadd.php',
        'category' => 'Пользователи',
        'desc' => 'Выдача инвайтов и контроль инвайтной системы.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Новости',
        'url' => 'news.php',
        'category' => 'Контент',
        'desc' => 'Публикация и редактирование новостей на главной странице.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Категории',
        'url' => 'category.php',
        'category' => 'Контент',
        'desc' => 'Управление деревом категорий раздач и служебными параметрами.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Теги',
        'url' => 'tags-admin.php',
        'category' => 'Контент',
        'desc' => 'Создание, правка и удаление внутренних тегов.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Смайлы',
        'url' => 'smiles.php',
        'category' => 'Контент',
        'desc' => 'Редактор смайлов и их отображения в интерфейсе.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'FAQ',
        'url' => 'admincp.php?op=faq',
        'category' => 'Контент',
        'desc' => 'Полное редактирование разделов и вопросов справки.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Каталог персон',
        'url' => 'persons.php',
        'category' => 'Контент',
        'desc' => 'Управление персонами, псевдонимами и связями с раздачами.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Список опросов',
        'url' => 'polls.php',
        'category' => 'Контент',
        'desc' => 'Все опубликованные опросы с возможностью редактирования.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Обзор голосов',
        'url' => 'polloverview.php',
        'category' => 'Контент',
        'desc' => 'Подробная расшифровка ответов по каждому опросу.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Создать опрос',
        'url' => 'makepoll.php',
        'category' => 'Контент',
        'desc' => 'Создание нового голосования и редактирование активного опроса.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Массовое ЛС',
        'url' => 'staffmess.php',
        'category' => 'Коммуникации',
        'desc' => 'Рассылка системных личных сообщений группам пользователей.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Очистить чат',
        'url' => 'clear.php',
        'category' => 'Коммуникации',
        'desc' => 'Быстрая очистка shoutbox и служебных сообщений.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Спам-контроль',
        'url' => 'spam.php',
        'category' => 'Коммуникации',
        'desc' => 'Поиск флуда, дублей и подозрительной массовой активности.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Баны',
        'url' => 'bans.php',
        'category' => 'Безопасность',
        'desc' => 'Управление банами и проверка заблокированных адресов.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Журнал hackers',
        'url' => 'hackers.php',
        'category' => 'Безопасность',
        'desc' => 'Просмотр событий антихака и подозрительных запросов.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Проверка IP',
        'url' => 'testip.php',
        'category' => 'Безопасность',
        'desc' => 'Поиск пересечений по IP и ручная проверка пользователей.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Пользователи за NAT',
        'url' => 'findnotconnectable.php',
        'category' => 'Безопасность',
        'desc' => 'Контроль проблем с connectable и NAT-окружением.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'AI-помощник',
        'url' => 'admincp.php?op=ai_helper',
        'category' => 'Безопасность',
        'desc' => 'Разбор логов, чата и аномальной активности прямо из админки.',
        'min_class' => UC_SYSOP,
        'badge' => 'AI',
    ],
    [
        'title' => 'Статистика',
        'url' => 'stats.php',
        'category' => 'Аналитика',
        'desc' => 'Сводка по раздачам, пользователям и общему состоянию трекера.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Лог сайта',
        'url' => 'log.php',
        'category' => 'Аналитика',
        'desc' => 'Журнал действий и служебных событий движка.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'История модерации',
        'url' => 'modded.php',
        'category' => 'Аналитика',
        'desc' => 'Детальный аудит модераторских и административных действий.',
        'min_class' => UC_MODERATOR,
    ],
    [
        'title' => 'Классы и права',
        'url' => 'admincp.php?op=class_permissions',
        'category' => 'Система',
        'desc' => 'Каталог классов, профили прав и переходящие кубки.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Операции с БД',
        'url' => 'admincp.php?op=database',
        'category' => 'Система',
        'desc' => 'Быстрый ремонт и оптимизация выбранных таблиц из admincp.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Статус таблиц БД',
        'url' => 'statusdb.php',
        'category' => 'Система',
        'desc' => 'Подробный список таблиц, размеров и массовая оптимизация.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Редактор конфигурации',
        'url' => 'config_editor.php',
        'category' => 'Система',
        'desc' => 'Управление ключевыми параметрами `include/config.php` через UI.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Бэкап БД',
        'url' => 'db_backup.php',
        'category' => 'Система',
        'desc' => 'Создание дампа базы и восстановление из SQL-файла.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Cleanup',
        'url' => 'docleanup.php',
        'category' => 'Система',
        'desc' => 'Ручной запуск служебной очистки и фоновых процедур.',
        'min_class' => UC_SYSOP,
    ],
    [
        'title' => 'Бонусный магазин',
        'url' => 'mybonus.php?action=elegor',
        'category' => 'Бонусы и игры',
        'desc' => 'Администрирование бонусных позиций, цен и типов наград.',
        'min_class' => UC_ADMINISTRATOR,
    ],
    [
        'title' => 'Супер-Лото',
        'url' => 'loto-start.php',
        'category' => 'Бонусы и игры',
        'desc' => 'Запуск и сопровождение розыгрышей Super Loto.',
        'min_class' => UC_ADMINISTRATOR,
    ],
];
