<?php
/***********************\
--DO NOT EDIT THIS FILE--
\***********************/

/**
 * Bridge с MyBB: создание пользователя и смена пароля.
 * Совместимо с TBDev / PHP 8.1 (mysqli).
 *
 * Ожидаемые define() от вызывающей стороны:
 *   REGISTER (guard) — уже есть
 *   TYPE one of:
 *     - 'add_forum_user'
 *     - 'change_forum_password'
 *     - 'change_forum_password_admin'
 *
 * Для add_forum_user должны быть заданы переменные:
 *   $id, $wantusername, $wantpassword, $email, $ip, $timezone, $enabledst, $use_email_act
 * Для change_forum_password: $CURUSER['id'], $chpassword
 * Для change_forum_password_admin: $userid, $chpassword
 */

// Защита от прямого вызова
if (!defined('REGISTER')) {
    die('Hacking attempt!');
}

/** Безопасная случайная строка (латиница + цифры, без 0/O/l/I) */
function random_str_c(int $length = 8): string {
    $chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ123456789';
    $max   = strlen($chars) - 1;
    $buf   = '';
    for ($i = 0; $i < $length; $i++) {
        $buf .= $chars[random_int(0, $max)];
    }
    return $buf;
}

/** MyBB login key */
function generate_loginkey(): string {
    return random_str_c(50);
}

/**
 * Хэш MyBB 1.x: md5(md5($salt) . $password_md5)
 * ВНИМАНИЕ: сюда должен приходить уже md5(plain_password) во 2м аргументе,
 * чтобы на выходе было md5(md5($salt) . md5($password)).
 */
function salt_password(string $password_md5, string $salt): string {
    return md5(md5($salt) . $password_md5);
}

/** Обновление пароля в MyBB */
function update_password(int $uid, string $password_md5, string $salt = ''): void {
    $saltedpw = salt_password($password_md5, $salt);
    $loginkey = generate_loginkey();
    sql_query(
        'UPDATE ' . TABLE_PREFIX . 'users
         SET password = ' . sqlesc($saltedpw) . ',
             loginkey = ' . sqlesc($loginkey) . '
         WHERE uid = ' . sqlesc($uid) . '
         LIMIT 1'
    );
}

/** Определяем тип действия: приоритет у константы TYPE (включение файла), затем запрос */
$type = defined('TYPE')
    ? (string)TYPE
    : (isset($_POST['type']) ? (string)$_POST['type'] : (isset($_GET['type']) ? (string)$_GET['type'] : ''));

if ($type === 'add_forum_user') {
    // ===== Добавление нового пользователя в форум =====
    $now      = time();
    $salt     = random_str_c();
    $loginkey = generate_loginkey();

    // Ожидается md5() от plain-пароля
    $wantpassword = $wantpassword ?? '';
    $wantusername = $wantusername ?? '';
    $email        = $email ?? '';
    $id           = isset($id) ? (int)$id : 0;
    $ip           = $ip ?? '0.0.0.0';
    $timezone     = $timezone ?? '0';
    $enabledst    = $enabledst ?? '0';
    $use_email_act = isset($use_email_act) ? (int)$use_email_act : 0;

    // Совместимость с твоей схемой: в INSERT используется md5(md5($salt).md5($wantpassword))
    $saltedpw = md5(md5($salt) . md5($wantpassword));

    // Группа пользователя
    if (defined('GROUP')) {
        $usergroup = (int)GROUP;
    } elseif ($use_email_act === 1) {
        $usergroup = defined('MYBB_PENDING') ? (int)MYBB_PENDING : 5; // fallback
    } elseif (defined('ACTIVATION') && ACTIVATION === 'no') {
        $usergroup = defined('MYBB_USER') ? (int)MYBB_USER : 2; // fallback
    } else {
        $usergroup = defined('MYBB_USER') ? (int)MYBB_USER : 2; // fallback
    }

    sql_query("
        INSERT INTO " . TABLE_PREFIX . "users (
            uid, username, password, salt, loginkey, email, usergroup, regdate, lastactive, lastvisit,
            allownotices, hideemail, emailnotify, receivepms, pmpopup, pmnotify, remember,
            showsigs, showavatars, showquickreply, invisible, style, daysprune, regip,
            showcodebuttons, tpp, ppp, referrer, timezone, dst
        ) VALUES (
            " . sqlesc($id) . ",
            " . sqlesc($wantusername) . ",
            " . sqlesc($saltedpw) . ",
            " . sqlesc($salt) . ",
            " . sqlesc($loginkey) . ",
            " . sqlesc($email) . ",
            " . sqlesc($usergroup) . ",
            $now, $now, $now,
            'yes','no','no','yes','yes','yes','yes',
            'yes','yes','yes','no','0','0'," . sqlesc($ip) . ",
            '1','0','0','0'," . sqlesc($timezone) . "," . sqlesc($enabledst) . "
        )
    ") or sqlerr(__FILE__, __LINE__);

    // Требуется активация по e-mail?
    if ($use_email_act === 1 && defined('ACTIVATION') && ACTIVATION === 'yes') {
        $activationcode = random_str_c();
        sql_query("
            INSERT INTO " . TABLE_PREFIX . "awaitingactivation (uid, dateline, code, type)
            VALUES (" . sqlesc($id) . ", $now, " . sqlesc($activationcode) . ", 'r')
        ") or sqlerr(__FILE__, __LINE__);
    }

} elseif ($type === 'change_forum_password') {
    // ===== Смена пароля пользователем =====
    global $CURUSER;
    if (!isset($CURUSER['id'])) {
        // Нет текущего пользователя — выходим тихо
        return;
    }
    $uid        = (int)$CURUSER['id'];
    $chpassword = $chpassword ?? '';

    $sql = sql_query("SELECT salt FROM " . TABLE_PREFIX . "users WHERE uid = " . sqlesc($uid) . " LIMIT 1");
    if ($sql && mysqli_num_rows($sql) >= 1) {
        $mybbuser = mysqli_fetch_assoc($sql);
        // Передаём md5(plain), как ожидает salt_password()
        update_password($uid, md5($chpassword), (string)$mybbuser['salt']);
        // $forumpassword = 1; // если где-то выше нужен флаг — можно выставить глобально
    }

} elseif ($type === 'change_forum_password_admin') {
    // ===== Смена пароля админом (как в recover.php) =====
    $userid     = isset($userid) ? (int)$userid : 0;
    $chpassword = $chpassword ?? '';

    if ($userid > 0 && $chpassword !== '') {
        $sql = sql_query("SELECT salt FROM " . TABLE_PREFIX . "users WHERE uid = " . sqlesc($userid) . " LIMIT 1");
        if ($sql && mysqli_num_rows($sql) >= 1) {
            $mybbuser = mysqli_fetch_assoc($sql);
            update_password($userid, md5($chpassword), (string)$mybbuser['salt']);
        }
    }
}
// конец файла
